apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - image: docker.io/datefix/vote:d85a6f886d763d3bf2eb3010e368cc354237c30b
        name: vote-ui
        ports:
        - containerPort: 80
